### ISSUE TITLE
Add support for optional parameter "filename"

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/upload-files-to-static-rdf-server-action#6]
Want to do this:
```
uses: Informasjonsforvaltning/upload-files-to-static-rdf-server-action@v2.1
with:
  ontology-type: "vocabulary"
  ontology: "hello-world"
  files: |
    testfiles/hello-world.ttl text/turtle en
    testfiles/hello-world-nb.ttl text/turtle nb
    testfiles/images/logo.png image/png nb images/logo.png
  host: "https://example.com"
  api-key: ${{ secrets.API_KEY }}
```
where the last string i the last file is the value of the optional `filename` parameter.

Should probably be implemented like
```
-F "ontology-file=@$file;type=$file_type;filename=images/logo.png;headers=\"content-language: $file_language\"" \
```
Ref second example here:
https://github.com/Informasjonsforvaltning/static-rdf-server#to-upload-content-to-the-server
