### ISSUE TITLE
Add support for optional parameter "version"

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/upload-files-to-static-rdf-server-action#8]
Desired usage:
```
uses: Informasjonsforvaltning/upload-files-to-static-rdf-server-action@v3.2.0
with:
  ontology-type: "vocabulary"
  ontology: "hello-world"
  version: "v1.1"
  files: |
    testfiles/hello-world.ttl text/turtle en
    testfiles/hello-world-nb.ttl text/turtle nb
  host: "https://example.com"
  api-key: ${{ secrets.API_KEY }}
```

If given, value of `version` should be last part of url:
```
url="${host}/${ontology_type}/${ontology}/${version}"
```
If `version` is undefined, url should be as before:
```
url="${host}/${ontology_type}/${ontology}"
```
